### ISSUE TITLE
Consider updating the repository description to be shorter, and move announcements/callouts to README?

### ISSUE THREAD

**Issue by pradyunsg** [pypa/distlib#158]
<img width="334" alt="Screenshot 2021-12-11 at 09 54 48" src="https://user-images.githubusercontent.com/3275593/145672304-3b1ff89f-1794-4244-a312-7c81dd078745.png">

The current description is difficult to read, due to the amount of content there. GitHub even truncates it. The information presented there seems to be something that might be beneficial to put into the README instead.

**Comment by pradyunsg** [comment]
You can also move the documentation URL to the dedicated URL field.

**Comment by vsajip** [comment]
Fair comment, I just did the minimum to get it moved over, intending to get things tidied up in due course.

**Comment by pradyunsg** [comment]
This has been done! :tada:
