### ISSUE TITLE
ScriptMaker.make cannot handle callable modules (ExportEntry.suffix is None)

### ISSUE THREAD

**Issue by saaketp** [pypa/distlib#163]
**Describe the bug**
`pip` uses a [subclass of distlib's `ScriptMaker`](https://github.com/pypa/pip/blob/22.0.4/src/pip/_internal/operations/install/wheel.py#L424) for making entry points when installing wheel files. But it needs to add an [extra check to disallow a `None` suffix](https://github.com/pypa/pip/blob/22.0.4/src/pip/_internal/operations/install/wheel.py#L426) because `ScriptMaker.make` assumes that suffix is a string [and tries to split it](https://github.com/pypa/pip/blob/22.0.4/src/pip/_vendor/distlib/scripts.py#L228-L230).

However if the module itself is callable, then the suffix can be `None`. The [entry points specification](https://packaging.python.org/en/latest/specifications/entry-points/) only requires that the entry point is callable, which means technically a callable module can also be an entry point.

The setuptools docs also suggest this https://setuptools.pypa.io/en/latest/userguide/entry_point.html
The syntax for entrypoints is `<name> = [<package>.[<subpackage>.]]<module>[:<object>.<object>]`, which means only the module part is mandatory and the `:object` suffix is optional. Also, editable installs with setuptools do produce a correct console entrypoints if a callable module is provided.

So, `pip` is not able to support callable modules as entrypoints when installing wheel files, because of this bug in distlib. See https://github.com/pypa/pip/issues/8632.

**To Reproduce**
1. `pip install pip==22.0.4`
2. `git clone https://github.com/saaketp/module-entrypoint.git`
3. Try installing in editable mode (`pip install -e ./module-entrypoint`) and notice that it works fine and makes a `module-entrypoint` executable.
4. Try installing again in non-editable mode (`pip install ./module-entrypoint`) and notice that this time it doesn't work because this time `PipScriptMaker.make` is used and it disallows entrypoint with `None` suffix.
```
ERROR: For req: module-entrypoint==0.0.1. Invalid script entry point: <ExportEntry module-entrypoint = module_entrypoint:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```
5. Comment out the [_raise_for_invalid_entrypoint check in `PipScriptMaker.make`](https://github.com/pypa/pip/blob/22.0.4/src/pip/_internal/operations/install/wheel.py#L426) and try `pip install ./module-entrypoint` again, and notice that now `distlib` throws an exception
```
ERROR: Exception:
Traceback (most recent call last):
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\commands\install.py", line 405, in run
    installed = install_given_reqs(
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\req\req_install.py", line 769, in install
    install_wheel(
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 729, in install_wheel
    _install_wheel(
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 646, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_vendor\distlib\scripts.py", line 428, in make_multiple
    filenames.extend(self.make(specification, options))
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 427, in make
    return super().make(specification, options)
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_vendor\distlib\scripts.py", line 417, in make
    self._make_script(entry, filenames, options=options)
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_vendor\distlib\scripts.py", line 311, in _make_script
    script = self._get_script_text(entry).encode('utf-8')
  File "D:\ss\Miniconda3\envs\py310\lib\site-packages\pip\_vendor\distlib\scripts.py", line 229, in _get_script_text
    import_name=entry.suffix.split('.')[0],
AttributeError: 'NoneType' object has no attribute 'split'
```

**Expected behavior**
After removing the suffix requirement from pip, the package should be installed properly with the entry point, instead of getting an exception from distlib.

**Screenshots**
NA

**Environment**
 - All OSes (tested on windows 10 only)
 - The latest version also has this issue, I tested with the version [vendored in pip 22.0.4](https://github.com/pypa/pip/tree/22.0.4/src/pip/_vendor/distlib)

**Additional information**
The script template also assumes that the suffix will always be there and that it can be imported as `from module import suffix`
https://github.com/pypa/pip/blob/22.0.4/src/pip/_vendor/distlib/scripts.py#L44
So the first step to fix this would probably be to change this to just `import module`. I haven't tried it properly yet.

**Comment by pradyunsg** [comment]
This is expected and is not a bug. See the link in pip's error message, which describes the additional restrictions: https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts

The attribute part of the entrypoint name is required for using with `console_scripts` and `gui_scripts`.

**Comment by saaketp** [comment]
So it could be updated to handle None suffixes without a lot of change it seems.
I submitted the change in #166

I'll understand if you want to close that and update the wording of the standard instead.

**Comment by a-gn** [comment]
My team also has a use case for this. It would simplify our packaging a bit. Based on the docs of setuptools, I had a hard time finding why this didn't work; I think it would be better to merge @saaketp 's PR than to change the documentation.

**Comment by vsajip** [comment]
@a-gn what is your use case? Modules aren't meant to be callable, though of course one can do `sys.modules[__name__] = func` to make it appear so. In the @saaketp example he could well have specified `module_entry_point:func` for the console script entry point. Not sure how that's less simple than specifying just the module.

**Comment by vsajip** [comment]
I'll close this, as there's been no response.
