### ISSUE TITLE
What is the license and copyright of pypi-server-standalone.py?

### ISSUE THREAD

**Issue by hexagonrecursion** [pypa/distlib#167]
**Is your feature request related to a problem? Please describe.**
You are vendoring tests/pypi-server-standalone.py. I could not find any information on where it came from or what its license and copyright status is.

**Describe the solution you'd like**
Tell me who owns the copyright and which license it it under and I'll add the metadata in my next PR.

**Additional context**
https://github.com/pypa/distlib/compare/master...hexagonrecursion:reuse?expand=1

**Comment by vsajip** [comment]
That information is [here](https://github.com/pypiserver/pypiserver/blob/master/LICENSE.txt).

**Comment by vsajip** [comment]
Closing, as answered in above comment.
