### ISSUE TITLE
Shouldn't `distlib.wheel.install` reuse the code from `installer` package?

### ISSUE THREAD

**Issue by KOLANICH** [pypa/distlib#190]
**Is your feature request related to a problem? Please describe.**
Currently there multiple packages achieving the same goal within the official `pypa` packages. It creates bloat and violates DRY principle.

**Describe the solution you'd like**
`distlib.wheel.install` becomes a facade for `installer`.

**Describe alternatives you've considered**
IMHO it doesn't make sense to migrate the content of `installer` into `distlib`. `distlib` is already too large (in the amount of things it does and concepts it introduces) and IMHO it may make sense to split it into multiple separate packages.

**Comment by vsajip** [comment]
The `distlib` wheel code (first committed in Feb 2013) pre-dates `installer` (Apr 2020), so the `installer` developers chose not to use existing and mature wheel code in `distlib`. In fact I believe they still copy and use `distlib`'s launcher executables.

>`distlib` is already too large (in the amount of things it does and concepts it introduces)

You're entitled to that opinion, but mine is that it's a library focused fairly narrowly around functionality related to package installation and ancillary stuff such as the installed package database, package metadata, versions, resource abstraction for Python packages, wheels and interfacing to PyPI.

You don't have to use all of `distlib`'s features if you don't want to or need to - and as far as "large" goes, it's not that big a package in terms of e.g. disk space used. I've tried to document features as best I can and remain open to suggestions for documentation improvements if suggested. As far as DRY is concerned, you only have to look at the proliferation of packaging tools with overlaps (e.g. PEP 517 builders) to see that DRY is not the most important criterion in the packaging landscape.

**Comment by KOLANICH** [comment]
>You're entitled to that opinion

I'm, and I have strong opinions on certain points. I have never wanted to offend anyone.

>The distlib wheel code (first committed in Feb 2013) pre-dates installer (Apr 2020)

Yeah, I know.

>so the installer developers chose not to use existing and mature wheel code in distlib.

I can hypohesize why they have done this. I guess they just wanted a package doing the single thing (and failed in it, since `installer` not only installs a wheel, but contains some abstractions to deal with them, which are incomplete, but IMHO deserve to be more complete and be in a separate package).

>library focused fairly narrowly around functionality related to package installation and ancillary stuff such as the installed package database, package metadata, versions, resource abstraction for Python packages, wheels and interfacing to PyPI.

Yes, it is focused around Python packages and is small in the count of files, and well integrated. But when I see the API reference, it produces the feeling of an aggregate of different libs, interdependent, using each other, but still different. It feels a bit odd.

>As far as DRY is concerned

DRY is a concern not only because of duplication and bloat, but also because of interoperability issues originating from the fact different libs can require objects of different classes doing the same things provided by different libs. It'd cause costs on abstraction layers around these different classes, and also convertors. It is nice when there is only 1 implementation for basic things.

An example of such an impl is `numpy`, all the scientific, ML and signal-processing packages are built around it and one can be sure that they can interoperate to each other because of the shared reperesentation provided by a separate package. Usually no conversions are needed, one can take an object created by one lib and feed it directly into ankther one.

An example of bad duplication is packages for version parsing. There are quite a lot of them, most of them make very specific assumptions on the format of a version number and on how a class should behave, one cannot compare versions parsed by different packages, and one may need to have all of them if one wants to deal with versions. I have even had to create an own one making as less assumptions about version strings as possible. It would be hard to clean all this mess.

Another example of bad duplication are packages for paths and console text styles. `colorama` somewhere is too dumb, somewhere it contains the features are not needed, so are `colored` and `plumbum.colorlib`. `rich` is large, monstrous and bloated. But is widely adopted. And they all contain lists of colors and their codes. Again in my `RichConsole` I didn't want to maintain the list of colors myself, so I have written the code importing the list of colors from other libs. It'd have been much better if there was one central package for the raw codes, not tied to a repr used in any specific lib, but just a database of codes. Unfortunately maintainers of libs have self-interests of promoting their libs, so they'd prefer to have own list of codes in own format with incompatible names rather than to have a shared one maintained jointly by all the authors of the libs, making it easier to switch libs and giving all the libs the same set of styles and colors.

Another example of bad duplication are analogues of `pathlib.Path`. We have `pathlib.Path`, but there were quite some packages supporting Python 2, and quite some of them were using an own analogue of `pathlib.Path`. Python 2 is long dead and decomposed, but these custom classes still haunt us.

I think that the (possibly abstract) classes that serve as middleware should have only 1 impl and there should be a consensus among package authors that this middleware should be used. It allows packages using the middleware to interoperate.

>you only have to look at the proliferation of packaging tools with overlaps (e.g. PEP 517 builders) to see that DRY is not the most important criterion in the packaging landscape.

I miss the old good times when the only build backend to be taken into account used to be `setuptools`. PEP 621 is good, but currently the packaging ecosystem has become a mess, I have to maintain some hacks (that break too often) and some abstraction layers.

**Comment by vsajip** [comment]
> I have never wanted to offend anyone.

No offence taken.

> But when I see the API reference, it produces the feeling of an aggregate of different libs, interdependent, using each other, but still different. It feels a bit odd.

That's because the different parts _are_ interdependent, because they handle different parts of related abstractions - they're all connected because they have to be. Some parts indeed are old - they came from the aborted `packaging` package in the Python 3.3 development cycle (unconnected to the `packaging` now on PyPI) - so I didn't create those APIs, just built on them.

> It is nice when there is only 1 implementation for basic things.

Sure, but you can't stop people doing their own thing, and other people using the alternatives created. Just look at `logging` in the stdlib - seems reasonably functional, was there in Python pretty much before any other logging functionality was established, and yet people have found the need to produce alternatives, which have vocal enthusiasts. It's just human nature ...

**Comment by KOLANICH** [comment]
@vsajip, I have created a review of Python packaging entities/concepts and support of features in libs. https://github.com/KOLANICH/python_packaging_review It may be helpful in:

* identifying missing specifications and creating them
* choosing libs for dealing with an entity related to packaging
* identifying missing features in libs and implementing them
* introducing newbies into the concepts

Could you and other PyPA people review it and maybe add something? Also I'd like to transfer it into PyPA docs repository.

**Comment by vsajip** [comment]
OK, thanks. I can't say when I'll find the time to do anything much, but I appreciate the effort you've put in and will try to look at `distlib`'s position in the matrix to see if anything needs correcting or updating.
