### ISSUE TITLE
Ability to select UNCHECKED_HASH or CHECKED_HASH for bytecode_hashed_invalidation option

### ISSUE THREAD

**Issue by wimglenn** [pypa/distlib#212]
[`distlib.wheel.Wheel.install()`](https://github.com/pypa/distlib/blob/0.3.8/distlib/wheel.py#L505-L520) currently allows specifying `bytecode_hashed_invalidation` but it's only a True/False option, passed to [`byte_compile`](https://github.com/pypa/distlib/blob/0.3.8/distlib/util.py#L609) to access [`py_compile.PycInvalidationMode.CHECKED_HASH`](https://docs.python.org/3/library/py_compile.html#py_compile.PycInvalidationMode.CHECKED_HASH) mode.

I want to use [`UNCHECKED_HASH`](https://docs.python.org/3/library/py_compile.html#py_compile.PycInvalidationMode.UNCHECKED_HASH) mode, because my .py/.pyc code live on a read-only filesystem and they've already been validated once at build-time.

Can the public API expose a way to specify `UNCHECKED_HASH` mode for the .pyc creation, to avoid wasteful/redundant hash checking at runtime?

**Comment by vsajip** [comment]
Would you like to propose a way to do this?

**Comment by wimglenn** [comment]
Added a proposal in https://github.com/pypa/distlib/pull/213
